### PR TITLE
(fix) fixed tests and upgraded to landing zone v6

### PR DESCRIPTION
**Pull request by vbontempi**
### Description

fixed tests setupOptions
upgraded to landing zone v6

### Release required?

- [X] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [x] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by rajatagarwal-ibm — APPROVED** [review]

**Review by ocofaigh — APPROVED** [review]

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@vbontempi To get pipeline to pass, you need to bump to landing zone v6. There is a renovate PR for this (https://github.com/terraform-ibm-modules/terraform-ibm-mq-operator/pull/78) but it failed as it needs the fix your adding in this PR.

Can you maybe update to landing zone v6 in this PR? Then tests should pass

**Comment by vbontempi** [comment]
> @vbontempi To get pipeline to pass, you need to bump to landing zone v6. There is a renovate PR for this (#78) but it failed as it needs the fix your adding in this PR.
> 
> Can you maybe update to landing zone v6 in this PR? Then tests should pass

done

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
